import { Inter } from 'next/font/google'
import '../css/tailwind.css'
import '../css/App.css'
import '../css/main.css'
import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container'>
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
